# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{steam}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Sven Fuchs", "Clemens Kofler"]
  s.date = %q{2010-02-21}
  s.description = %q{Steam is a headless integration testing tool driving HtmlUnit to enable testing JavaScript-driven web sites.}
  s.email = %q{svenfuchs@artweb-design.de}
  s.extra_rdoc_files = [
    "README.textile",
     "TODO"
  ]
  s.files = [
    "MIT-LICENSE",
     "README.textile",
     "Rakefile",
     "TODO",
     "lib/core_ext/ruby/array/flatten_once.rb",
     "lib/core_ext/ruby/hash/except.rb",
     "lib/core_ext/ruby/hash/slice.rb",
     "lib/core_ext/ruby/kernel/silence_warnings.rb",
     "lib/core_ext/ruby/process/daemon.rb",
     "lib/core_ext/ruby/string/camelize.rb",
     "lib/core_ext/ruby/string/underscore.rb",
     "lib/steam.rb",
     "lib/steam/browser.rb",
     "lib/steam/browser/html_unit.rb",
     "lib/steam/browser/html_unit/actions.rb",
     "lib/steam/browser/html_unit/client.rb",
     "lib/steam/browser/html_unit/connection.rb",
     "lib/steam/browser/html_unit/drb.rb",
     "lib/steam/browser/html_unit/matchers.rb",
     "lib/steam/browser/html_unit/page.rb",
     "lib/steam/browser/html_unit/web_response.rb",
     "lib/steam/connection.rb",
     "lib/steam/connection/mock.rb",
     "lib/steam/connection/net_http.rb",
     "lib/steam/connection/open_uri.rb",
     "lib/steam/connection/rails.rb",
     "lib/steam/connection/static.rb",
     "lib/steam/java.rb",
     "lib/steam/process.rb",
     "lib/steam/request.rb",
     "lib/steam/response.rb",
     "lib/steam/session.rb",
     "lib/steam/session/rails.rb",
     "lib/steam/version.rb"
  ]
  s.homepage = %q{http://github.com/svenfuchs/steam}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Headless integration testing w/ HtmlUnit: enables testing JavaScript-driven web sites}
  s.test_files = [
    "test/all.rb",
     "test/browser/html_unit/actions_test.rb",
     "test/browser/html_unit/javascript_test.rb",
     "test/browser/html_unit/rails_actions_test.rb",
     "test/browser/html_unit_test.rb",
     "test/connection/cascade_test.rb",
     "test/connection/mock_test.rb",
     "test/connection/rails_test.rb",
     "test/connection/static_test.rb",
     "test/fixtures/html_fakes.rb",
     "test/java_test.rb",
     "test/playground/connection.rb",
     "test/playground/dragdrop_behavior.rb",
     "test/playground/drb.rb",
     "test/playground/java_signature.rb",
     "test/playground/nokogiri.rb",
     "test/playground/put_headers.rb",
     "test/playground/rack.rb",
     "test/playground/rjb_bind.rb",
     "test/playground/stack_level_problem.rb",
     "test/playground/thread_problem.rb",
     "test/playground/web_response_data.rb",
     "test/playground/webrat.rb",
     "test/playground/xhr_accept_headers.rb",
     "test/process_test.rb",
     "test/session_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rjb>, [">= 1.2.0"])
      s.add_runtime_dependency(%q<locator>, [">= 0.0.4"])
    else
      s.add_dependency(%q<rjb>, [">= 1.2.0"])
      s.add_dependency(%q<locator>, [">= 0.0.4"])
    end
  else
    s.add_dependency(%q<rjb>, [">= 1.2.0"])
    s.add_dependency(%q<locator>, [">= 0.0.4"])
  end
end

